main:
  components_repository: "https://github.com/CAMM961001/my_website"
  streamlit: "https://streamlit.io/"
  copyright: "Miguel Castaneda 2023"
  project_name: my_website
  steps: all

social_media:
  github: "https://github.com/CAMM961001"
  linkedin: "https://www.linkedin.com/in/miguel-angel-castaneda-martinez-b0a566142/"
  tweeter: "https://twitter.com/MiguelCast1234"

styling:
  page_title: "Miguel Castañeda"
  layout: "wide"
  pages: ["Portfolio","About Me"]
  menu_icons: ["house", "folder2-open"]

path:
  resume: "docs/resume.pdf"
  portfolio: "docs/portfolio.json"
  timeline: "docs/timeline.json"

images:
  profile: "images/profile.png"
  timeline: "images/timeline.png"
  analytics: "images/analytics.png"
  development: "images/development.png"
  bi: "images/bi.png"
  cloud: "images/cloud.png"
  colors:
    blue: "#8acade"
    green: "#d3ffce"
    pink: "#eebbff"
    orange: "#f5a623"
