main:
  components_repository: "https://github.com/CAMM961001/my_website"
  streamlit: "https://streamlit.io/"
  copyright: "Miguel Castaneda 2023"
  project_name: my_website
  steps: all

social_media:
  github: "https://github.com/CAMM961001"
  linkedin: "https://www.linkedin.com/in/miguel-angel-castaneda-martinez-b0a566142/"
  tweeter: "https://twitter.com/MiguelCast1234"

styling:
  page_title: "Miguel Castañeda Martínez"
  layout: "wide"
  pages: ['About Me','Portfolio']
  menu_icons: ['house', 'folder2-open']
  fontsize: [20]

path:
  resume: "docs/resume.pdf"
