main:
  components_repository: "https://github.com/CAMM961001/my_website"
  streamlit: "https://streamlit.io/"
  copyright: "Miguel Castañeda 2023"
  project_name: my_website
  steps: all

social_media:
  github: "https://github.com/CAMM961001"
  linkedin: "https://www.linkedin.com/in/miguel-angel-castaneda-martinez-b0a566142/"
  twitter: "https://twitter.com/MiguelCast1234"
  youtube: "https://www.youtube.com/channel/UCrgbPO8HEhtIlVfXT-DZrSg"

styling:
  page_title: "Miguel Castañeda"
  layout: "wide"
  pages: ["Portfolio","About Me"]
  menu_icons: ["house", "folder2-open"]

path:
  resume: "docs/resume.pdf"
  portfolio: "docs/portfolio.json"
  timeline: "docs/timeline.csv"

images:
  profile: "images/profile.png"
  skills: "images/icons/skills.png"
  timeline: "images/timeline.png"
  colors:
    blue: "#8acade"
    green: "#d3ffce"
    pink: "#eebbff"
    orange: "#f5a623"
